version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
     - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  gotour:
    image: sonbui00/docker-gotour
    #build: .
    container_name: gotour
    environment:
      - VIRTUAL_HOST=tour.golangvn.org
      - VIRTUAL_PORT=3999
